name: Frontend build

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - '*'
      - '*/*'
      - '**'
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - 'master'
      - 'develop'

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm --prefix frontend/ ci
      - run: npm --prefix frontend/ test

      - name: Docker login to registry
        run: docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u nologin -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Docker build frontend
        run: docker build -f frontend/Dockerfile.front --no-cache --progress=plain -t ${{ secrets.DOCKER_REGISTRY_URL }}/my-portfolio-frontend:${{ github.sha }} .

      - name: Push Docker frontend image to registry
        run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/my-portfolio-frontend:${{ github.sha }}

      - name: Kubernetes login
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_ALEXISDETRIE_DEV }}

      - name: Deploy frontend to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            frontend/src/main/kubernetes/deployment-frontend.yml
            frontend/src/main/kubernetes/ingress-frontend.yml
          images: |
            ${{ secrets.DOCKER_REGISTRY_URL }}/my-portfolio-frontend:${{ github.sha }}