name: Frontend build

on:
  workflow_dispatch:
  push:
    paths:
      - frontend
  pull_request:
    branches:
      - 'master'
      - 'develop'

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm --prefix frontend/ ci
      - run: npm --prefix frontend/ test
      - run: npm --prefix frontend/ run build

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login to registry
        run: docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u nologin -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Docker build frontend
        run: docker build -f frontend/Dockerfile.front --no-cache --progress=plain -t ${{ secrets.DOCKER_REGISTRY_URL }}/my-portfolio-frontend:${{ github.sha }} .
      - name: Push Docker frontend image to registry
        run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/my-portfolio-frontend:${{ github.sha }}

  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Kubernetes login
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_ALEXISDETRIE_DEV }}
      - name: Deploy frontend to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            frontend/kubernetes/deployment-frontend.yml
            frontend/kubernetes/ingress-frontend.yml
          images: |
            ${{ secrets.DOCKER_REGISTRY_URL }}/my-portfolio-frontend:${{ github.sha }}