name: Maven / package -P native

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build native image with Maven
        run: mvn package -Pnative
      - name: Docker login to registry
        run: docker login ${{ secrets.CONTAINER_IMAGE_REGISTRY }} -u ${{ secrets.DOCKER_REGISTRY_LOGIN }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build Docker image
        run: docker build -f src/main/docker/Dockerfile.native-micro -t alexisdetrie-dev/portfolio-function .
      - name: Tag Docker image
        run: docker tag alexisdetrie-dev/portfolio-function ${{ secrets.CONTAINER_IMAGE_REGISTRY }}/alexisdetrie-dev/portfolio-function:latest
      - name: Push Docker image to registry
        run: docker push ${{ secrets.CONTAINER_IMAGE_REGISTRY }}/alexisdetrie-dev/portfolio-function:latest