name: Maven / package -P native

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '**'
  pull_request:
    branches: 
      - 'master'
      - 'develop'

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build native image with Maven
        run: mvn package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true
      - name: Docker login to registry
        run: docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u nologin -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push Docker image to registry
        run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/my-portfolio-backend:latest

      - name: Docker build frontend
        run: docker build -f src/main/docker/Dockerfile.front --no-cache --progress=plain -t ${{ secrets.DOCKER_REGISTRY_URL }}/my-portfolio-frontend:latest .
      - name: Push Docker front image to registry
        run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/my-portfolio-frontend:latest

      - name: Kubernetes login
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_ALEXISDETRIE_DEV }}
      - name: Deploy app to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            src/main/kubernetes/deployment-backend.yml
            src/main/kubernetes/ingress-backend.yml
            src/main/kubernetes/deployment-frontend.yml
            src/main/kubernetes/ingress-frontend.yml
          force: true
